import "./globals.css";
import { Nunito_Sans } from "next/font/google";
import Header from "@/components/Header";

const nunito = Nunito_Sans({
  weight: ["300", "600", "800"],
  subsets: ["latin"],
  variable: "--font-nunito-sans",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${nunito.className} bg-veryLightGrayLMBG`}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
